# Generated by Django 2.2.2 on 2019-06-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=1000)),
                ('pub_data', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
