# Generated by Django 2.2.2 on 2019-06-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
