# Generated by Django 2.2.2 on 2019-06-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190621_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='author', max_length=100),
        ),
    ]
